dialect "java"

import domain.*;
import java.util.ArrayList;
import org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScoreHolder;

global HardSoftScoreHolder scoreHolder;

/***************************** HARD CONSTRAINTS *********************************/
rule "elke inschrijving moet een tijdslot toegewezen hebben"
    when
        $inschrijving : Inschrijving( tijdslot == null )
    then
        scoreHolder.addHardConstraintMatch(kcontext, -8);
end

rule "geen twee inschrijvingen voor een AFDELING op het zelfde moment"
    when
        $leftInschrijving : Inschrijving (
            $id : id,
            tijdslot != null,
            $tijdslot : tijdslot,
            $leftId : afdeling.naam,
            $afdeling : afdeling,
            $leftJongens: discipline.isJongens(),
            $leftMeisjes: discipline.isMeisjes())
        $rightInschrijving : Inschrijving(
            id > $id,
            afdeling == $afdeling,
            tijdslot != null,
            $rightJongens : discipline.isJongens(),
            $rightMeisjes : discipline.isMeisjes(),
            $rightTijdslot : tijdslot,
            ($leftJongens == true && $rightJongens == true) ||
            ($leftMeisjes == true && $rightMeisjes == true),
            tijdslot.isOverlap($tijdslot))
    then
        scoreHolder.addHardConstraintMatch(kcontext, -6);
end

rule "geen twee inschrijvingen voor een RING op het zelfde moment"
    when
        $leftInschrijving : Inschrijving(
            tijdslot != null,
            $leftId : id,
            $ring : ring)
        $rightInschrijving : Inschrijving(
            tijdslot != null,
            ring == $ring,
            tijdslot.isOverlap($leftInschrijving.tijdslot),
            id > $leftId)
    then
        scoreHolder.addHardConstraintMatch(kcontext, -4);
end
